name: release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pypi:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      # Required for PyPI trusted publishing (OIDC).
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.13"
      - run: python -m pip install --upgrade pip build
      - run: python -m build
      - uses: pypa/gh-action-pypi-publish@a892a5a61159132606e93a2fa6f4358831b04d26 # v1.14.2
